name: conditionnal-workflow

on: 
  push:

jobs:
  build:
    name: build project
    runs-on: ubuntu-24.04

    steps:
      - run: echo "Lancement du build"


  tell-time:
    name: display launch time
    runs-on: ubuntu-24.04

    steps:
      - name: Show Current Date
        run: |
          echo "Current Date:" 
          date
          echo "Triggered by: ${{ github.actor }}"



  success-job:
    name: Job qui marche
    if: vars.WATER == 'cold'
    runs-on: ubuntu-24.04
    
    steps:
      - run: echo "Ca marche l'eau est froide"

  
  
  failed-job:
    name: Job qui echoue
    if: vars.WATER == 'warm'

    runs-on: ubuntu-24.04
    steps:
      - run: echo "Ca ne marche pas l'eau est chaude"

