name: Workflow cassé
on:
  -  workflow_dispatch
env:
  MA_VARIABLE: "valeur_test"
  MY_SECRET: "secret_value"

jobs:
  build_job:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Afficher variable
        run: echo "${{ env.MA_VARIABLE }}"
      - name: Test commande
        run: |
          echo "Hello World"
          if [ true ]; then echo "Vrai" ; fi
        
  test-job:
    runs-on: ubuntu-slim
    needs: build_job
    steps:
      - name: Test
        run: echo "Test"
